### ISSUE TITLE
Different characters to signify parallelism

### ISSUE THREAD

**Issue by lowlydba** [channeladvisor/sqltop#3]
In the [process list](https://github.com/channeladvisor/sqltop#process-list) section,

https://github.com/channeladvisor/sqltop/blob/main/sqltop.psm1#L612 

It might be more self-explanatory/accurate if `==>` was used instead of `-->` to denote parallelism, since that more closely resembles the icons used in query plans. Switching the arrow direction may also help. 

![image](https://user-images.githubusercontent.com/16843041/119572801-51753a00-bd81-11eb-8dba-cb0247e6bf24.png)

**Comment by m82labs** [comment]
This was not meant to represent anything shown in execution plans, it was simply meant to be a visual indicator that the session has multiple workers associated with it.
